"use client";
import Link from "next/link";
import {useSearchParams,useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import type {Evaluation} from "@/lib/contract";
import {sortMaster,type MasterTableRow} from "@/lib/master";
import {readModelFavorites,subscribeToModelFavorites,writeModelFavorites} from "@/lib/model-favorites";

const costFormatter=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});

export default function MasterLeaderboard({rows,evaluations,costCapturedAt}:{rows:MasterTableRow[];evaluations:Evaluation[];costCapturedAt:string}){
  const params=useSearchParams(),router=useRouter();
  const [favorites,setFavorites]=useState<string[]>([]),[favoriteNotice,setFavoriteNotice]=useState("");
  useEffect(()=>{const refresh=()=>setFavorites(readModelFavorites());refresh();return subscribeToModelFavorites(refresh);},[]);
  const q=(params.get("mq")??"").slice(0,200),provider=params.get("mp")??"",favoritesOnly=params.get("mf")==="1";
  const defaultSort=evaluations.some(e=>e.id==="intelligence-index")?"intelligence-index":"model";
  const requested=params.get("ms")??defaultSort,sort=["model","provider","intelligence-index-cost",...evaluations.map(e=>e.id)].includes(requested)?requested:defaultSort;
  const direction=params.get("md")==="desc"?"desc":"asc";
  const size=[25,50,100].includes(Number(params.get("mz")))?Number(params.get("mz")):25;
  const sorted=sortMaster(rows.filter(r=>(!provider||r.provider===provider)&&r.model.toLowerCase().includes(q.toLowerCase())&&(!favoritesOnly||favorites.includes(r.identity_key))),sort,direction);
  const pages=Math.max(1,Math.ceil(sorted.length/size)),page=Math.min(pages,Math.max(1,Math.floor(Number(params.get("mi"))||1)));
  const update=(values:Record<string,string|number>)=>{const next=new URLSearchParams(params.toString());next.set("mi","1");for(const [k,v]of Object.entries(values)){if(v==="")next.delete(k);else next.set(k,String(v));}router.replace(`/?${next}#master-leaderboard`,{scroll:false});};
  const stateHref=`/?${params.toString()}#master-leaderboard`;
  const toggleFavorite=(identity:string)=>{const next=favorites.includes(identity)?favorites.filter(id=>id!==identity):[...favorites,identity];if(writeModelFavorites(next)){setFavorites(next);setFavoriteNotice("");}else setFavoriteNotice("Favorites could not be saved in this browser.");};
  const header=(key:string,label:string,sticky?:string)=><th scope="col" className={sticky??"numeric"} aria-sort={sort===key?(direction==="asc"?"ascending":"descending"):"none"}><button onClick={()=>update({ms:key,md:sort===key&&direction==="asc"?"desc":"asc"})}>{label} {sort===key?(direction==="asc"?"↑":"↓"):"↕"}</button></th>;
  const costDate=new Date(`${costCapturedAt.slice(0,10)}T00:00:00Z`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});
  return <section id="master-leaderboard" className="panel master"><div className="eyebrow">Ranks by evaluation</div><h2>Master leaderboard</h2><p>Each evaluation column shows the model’s original rank. Cost per Intelligence Index task is the source-reported weighted average in USD. Sort by model, provider, evaluation rank, or cost. <Link href="/about/data">Data notes</Link>.</p>
    <div className="toolbar"><label className="sr-only" htmlFor="master-search">Search master model names</label><input id="master-search" value={q} placeholder="Search model names…" onChange={e=>update({mq:e.target.value})}/><label className="sr-only" htmlFor="master-provider">Master provider</label><select id="master-provider" value={provider} onChange={e=>update({mp:e.target.value})}><option value="">All providers</option>{[...new Set(rows.map(r=>r.provider))].sort().map(p=><option key={p}>{p}</option>)}</select><label className="sr-only" htmlFor="master-favorites">Favorite filter</label><select id="master-favorites" value={favoritesOnly?"favorites":"all"} onChange={e=>update({mf:e.target.value==="favorites"?"1":""})}><option value="all">All models</option><option value="favorites">Favorites only</option></select><strong>{favorites.length} favorite{favorites.length===1?"":"s"}</strong><button onClick={()=>update({mq:"",mp:"",mf:"",ms:"",md:"",mi:"",mz:""})}>Clear filters</button><Link href={stateHref}>Link to this view</Link></div>
    <p aria-live="polite">{sorted.length.toLocaleString()} models{favoritesOnly?` · ${favorites.length} favorites saved in this browser`:""} · Ranks come directly from the workbook. “Not ranked” means no entry exists for that exact model variant.</p>{favoriteNotice&&<p role="status">{favoriteNotice}</p>}
    <div className="table-scroll" role="region" aria-label="Master leaderboard, scroll horizontally for evaluations" tabIndex={0}><table><caption className="sr-only">Model ranks and Intelligence Index task costs across every evaluation</caption><thead><tr>{header("model","Model","master-model")}{header("provider","Provider","master-provider")}<th scope="col" className="numeric" aria-sort={sort==="intelligence-index-cost"?(direction==="asc"?"ascending":"descending"):"none"}><button title={`Artificial Analysis model profile values · captured ${costDate}`} onClick={()=>update({ms:"intelligence-index-cost",md:sort==="intelligence-index-cost"&&direction==="asc"?"desc":"asc"})}>Cost per Intelligence Index task {sort==="intelligence-index-cost"?(direction==="asc"?"↑":"↓"):"↕"}<small>USD · AA · {costDate}</small></button></th>{evaluations.map(e=><th key={e.id} scope="col" className="numeric" aria-sort={sort===e.id?(direction==="asc"?"ascending":"descending"):"none"}><button title={`Original source rank · captured ${e.captured_at}`} onClick={()=>update({ms:e.id,md:sort===e.id&&direction==="asc"?"desc":"asc"})}>{e.display_name} {sort===e.id?(direction==="asc"?"↑":"↓"):"↕"}<small>Rank · {e.captured_at}</small></button></th>)}</tr></thead><tbody>{sorted.slice((page-1)*size,page*size).map(r=><tr key={r.model_id}><td className="master-model"><button className="favorite-star" type="button" aria-pressed={favorites.includes(r.identity_key)} aria-label={`${favorites.includes(r.identity_key)?"Remove":"Add"} ${r.model} to favorites`} title={`${favorites.includes(r.identity_key)?"Remove from":"Add to"} favorites`} onClick={()=>toggleFavorite(r.identity_key)}>{favorites.includes(r.identity_key)?"★":"☆"}</button> <Link href={`/?mq=${encodeURIComponent(r.model)}&mp=${encodeURIComponent(r.provider)}#master-leaderboard`}>{r.model}</Link></td><td className="master-provider">{r.provider}</td><td className="numeric">{r.intelligence_index_cost?<a href={r.intelligence_index_cost.url} target="_blank" rel="noreferrer" title={`Artificial Analysis profile for ${r.intelligence_index_cost.model}`}>{costFormatter.format(r.intelligence_index_cost.cost_usd)}</a>:<span className="muted">—</span>}</td>{evaluations.map(e=>{const c=r.cells[e.id];return <td key={e.id} className="numeric">{c?<Link className="source-rank" href={c.href} title={c.entry.scoring_status??"Original source rank"} aria-label={`${r.model}, ${e.display_name}, original source rank ${c.entry.source_rank}`}>#{c.entry.source_rank}</Link>:<span className="muted">Not ranked</span>}</td>;})}</tr>)}{!sorted.length&&<tr><td className="empty" colSpan={evaluations.length+3}>No models match these filters.</td></tr>}</tbody></table></div>
    <div className="pager"><label>Rows per page <select value={size} onChange={e=>update({mz:e.target.value})}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><div><span>Page {page} of {pages}</span><button disabled={page===1} onClick={()=>update({mi:page-1})}>Previous</button><button disabled={page===pages} onClick={()=>update({mi:page+1})}>Next</button></div></div>
  </section>;
}
